AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: DevOpsUI lamdbada with spring boot.

Resources:
  LambdaSpringBootFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: devopsui.LambdaHandler::handleRequest
      Runtime: java8
      CodeUri: target/devopsui-0.0.1-SNAPSHOT.jar
      MemorySize: 1512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 60
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  LambdaSpringBootApi:
    Description: URL for application
    Value: !Sub 'https://pdp.execute-api.${AWS::Region}.amazonaws.com/'
    Export:
      Name: LambdaSpringBootJavaApp